<?php
// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

namespace GetStream\Tests;

use PHPUnit\Framework\TestCase;
use GetStream\Generated\Webhook;

class WebhookTest extends TestCase
{
    private string $secret = 'test-webhook-secret';
    private string $body = '{"type":"test.event"}';

    private function computeSignature(string $body, string $secret): string
    {
        return hash_hmac('sha256', $body, $secret);
    }

    public function testVerifySignatureValid(): void
    {
        $signature = $this->computeSignature($this->body, $this->secret);
        $this->assertTrue(Webhook::verifySignature($this->body, $signature, $this->secret));
    }

    public function testVerifySignatureWrongSignature(): void
    {
        $this->assertFalse(Webhook::verifySignature($this->body, 'invalidsignature', $this->secret));
    }

    public function testVerifySignatureTamperedBody(): void
    {
        $signature = $this->computeSignature($this->body, $this->secret);
        $this->assertFalse(Webhook::verifySignature('{"type":"tampered"}', $signature, $this->secret));
    }

    public function testVerifySignatureWrongSecret(): void
    {
        $signature = $this->computeSignature($this->body, $this->secret);
        $this->assertFalse(Webhook::verifySignature($this->body, $signature, 'wrong-secret'));
    }

    public function testVerifySignatureEmptySignature(): void
    {
        $this->assertFalse(Webhook::verifySignature($this->body, '', $this->secret));
    }

    public function testGetEventTypeValid(): void
    {
        $this->assertEquals('message.new', Webhook::getEventType('{"type":"message.new"}'));
    }

    public function testGetEventTypeFromArray(): void
    {
        $this->assertEquals('message.new', Webhook::getEventType(['type' => 'message.new']));
    }

    public function testGetEventTypeMissingField(): void
    {
        $this->assertNull(Webhook::getEventType('{"foo":"bar"}'));
    }

    public function testGetEventTypeInvalidJson(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        Webhook::getEventType('not json');
    }

    public function testGetEventTypeEmptyObject(): void
    {
        $this->assertNull(Webhook::getEventType('{}'));
    }

    /**
     * @dataProvider webhookEventProvider
     */
    public function testParseWebhookEvent(string $eventType, string $expectedClassName): void
    {
        $payload = '{"type":"' . $eventType . '"}';
        $event = Webhook::parseWebhookEvent($payload);
        $this->assertNotNull($event);
        $parts = explode('\\', get_class($event));
        $this->assertEquals($expectedClassName, end($parts));
    }

    public static function webhookEventProvider(): array
    {
        return [
            '*' => ['*', 'CustomEvent'],
            'appeal.accepted' => ['appeal.accepted', 'AppealAcceptedEvent'],
            'appeal.created' => ['appeal.created', 'AppealCreatedEvent'],
            'appeal.rejected' => ['appeal.rejected', 'AppealRejectedEvent'],
            'call.accepted' => ['call.accepted', 'CallAcceptedEvent'],
            'call.blocked_user' => ['call.blocked_user', 'BlockedUserEvent'],
            'call.closed_caption' => ['call.closed_caption', 'ClosedCaptionEvent'],
            'call.closed_captions_failed' => ['call.closed_captions_failed', 'CallClosedCaptionsFailedEvent'],
            'call.closed_captions_started' => ['call.closed_captions_started', 'CallClosedCaptionsStartedEvent'],
            'call.closed_captions_stopped' => ['call.closed_captions_stopped', 'CallClosedCaptionsStoppedEvent'],
            'call.created' => ['call.created', 'CallCreatedEvent'],
            'call.deleted' => ['call.deleted', 'CallDeletedEvent'],
            'call.dtmf' => ['call.dtmf', 'CallDTMFEvent'],
            'call.ended' => ['call.ended', 'CallEndedEvent'],
            'call.frame_recording_failed' => ['call.frame_recording_failed', 'CallFrameRecordingFailedEvent'],
            'call.frame_recording_ready' => ['call.frame_recording_ready', 'CallFrameRecordingFrameReadyEvent'],
            'call.frame_recording_started' => ['call.frame_recording_started', 'CallFrameRecordingStartedEvent'],
            'call.frame_recording_stopped' => ['call.frame_recording_stopped', 'CallFrameRecordingStoppedEvent'],
            'call.hls_broadcasting_failed' => ['call.hls_broadcasting_failed', 'CallHLSBroadcastingFailedEvent'],
            'call.hls_broadcasting_started' => ['call.hls_broadcasting_started', 'CallHLSBroadcastingStartedEvent'],
            'call.hls_broadcasting_stopped' => ['call.hls_broadcasting_stopped', 'CallHLSBroadcastingStoppedEvent'],
            'call.kicked_user' => ['call.kicked_user', 'KickedUserEvent'],
            'call.live_started' => ['call.live_started', 'CallLiveStartedEvent'],
            'call.member_added' => ['call.member_added', 'CallMemberAddedEvent'],
            'call.member_removed' => ['call.member_removed', 'CallMemberRemovedEvent'],
            'call.member_updated' => ['call.member_updated', 'CallMemberUpdatedEvent'],
            'call.member_updated_permission' => ['call.member_updated_permission', 'CallMemberUpdatedPermissionEvent'],
            'call.missed' => ['call.missed', 'CallMissedEvent'],
            'call.moderation_blur' => ['call.moderation_blur', 'CallModerationBlurEvent'],
            'call.moderation_warning' => ['call.moderation_warning', 'CallModerationWarningEvent'],
            'call.notification' => ['call.notification', 'CallNotificationEvent'],
            'call.permission_request' => ['call.permission_request', 'PermissionRequestEvent'],
            'call.permissions_updated' => ['call.permissions_updated', 'UpdatedCallPermissionsEvent'],
            'call.reaction_new' => ['call.reaction_new', 'CallReactionEvent'],
            'call.recording_failed' => ['call.recording_failed', 'CallRecordingFailedEvent'],
            'call.recording_ready' => ['call.recording_ready', 'CallRecordingReadyEvent'],
            'call.recording_started' => ['call.recording_started', 'CallRecordingStartedEvent'],
            'call.recording_stopped' => ['call.recording_stopped', 'CallRecordingStoppedEvent'],
            'call.rejected' => ['call.rejected', 'CallRejectedEvent'],
            'call.ring' => ['call.ring', 'CallRingEvent'],
            'call.rtmp_broadcast_failed' => ['call.rtmp_broadcast_failed', 'CallRtmpBroadcastFailedEvent'],
            'call.rtmp_broadcast_started' => ['call.rtmp_broadcast_started', 'CallRtmpBroadcastStartedEvent'],
            'call.rtmp_broadcast_stopped' => ['call.rtmp_broadcast_stopped', 'CallRtmpBroadcastStoppedEvent'],
            'call.session_ended' => ['call.session_ended', 'CallSessionEndedEvent'],
            'call.session_participant_count_updated' => ['call.session_participant_count_updated', 'CallSessionParticipantCountsUpdatedEvent'],
            'call.session_participant_joined' => ['call.session_participant_joined', 'CallSessionParticipantJoinedEvent'],
            'call.session_participant_left' => ['call.session_participant_left', 'CallSessionParticipantLeftEvent'],
            'call.session_started' => ['call.session_started', 'CallSessionStartedEvent'],
            'call.stats_report_ready' => ['call.stats_report_ready', 'CallStatsReportReadyEvent'],
            'call.transcription_failed' => ['call.transcription_failed', 'CallTranscriptionFailedEvent'],
            'call.transcription_ready' => ['call.transcription_ready', 'CallTranscriptionReadyEvent'],
            'call.transcription_started' => ['call.transcription_started', 'CallTranscriptionStartedEvent'],
            'call.transcription_stopped' => ['call.transcription_stopped', 'CallTranscriptionStoppedEvent'],
            'call.unblocked_user' => ['call.unblocked_user', 'UnblockedUserEvent'],
            'call.updated' => ['call.updated', 'CallUpdatedEvent'],
            'call.user_feedback_submitted' => ['call.user_feedback_submitted', 'CallUserFeedbackSubmittedEvent'],
            'call.user_muted' => ['call.user_muted', 'CallUserMutedEvent'],
            'campaign.completed' => ['campaign.completed', 'CampaignCompletedEvent'],
            'campaign.started' => ['campaign.started', 'CampaignStartedEvent'],
            'channel.created' => ['channel.created', 'ChannelCreatedEvent'],
            'channel.deleted' => ['channel.deleted', 'ChannelDeletedEvent'],
            'channel.frozen' => ['channel.frozen', 'ChannelFrozenEvent'],
            'channel.hidden' => ['channel.hidden', 'ChannelHiddenEvent'],
            'channel.max_streak_changed' => ['channel.max_streak_changed', 'MaxStreakChangedEvent'],
            'channel.muted' => ['channel.muted', 'ChannelMutedEvent'],
            'channel.truncated' => ['channel.truncated', 'ChannelTruncatedEvent'],
            'channel.unfrozen' => ['channel.unfrozen', 'ChannelUnFrozenEvent'],
            'channel.unmuted' => ['channel.unmuted', 'ChannelUnmutedEvent'],
            'channel.updated' => ['channel.updated', 'ChannelUpdatedEvent'],
            'channel.visible' => ['channel.visible', 'ChannelVisibleEvent'],
            'channel_batch_update.completed' => ['channel_batch_update.completed', 'ChannelBatchCompletedEvent'],
            'channel_batch_update.started' => ['channel_batch_update.started', 'ChannelBatchStartedEvent'],
            'custom' => ['custom', 'CustomVideoEvent'],
            'export.bulk_image_moderation.error' => ['export.bulk_image_moderation.error', 'AsyncExportErrorEvent'],
            'export.bulk_image_moderation.success' => ['export.bulk_image_moderation.success', 'AsyncBulkImageModerationEvent'],
            'export.channels.error' => ['export.channels.error', 'AsyncExportErrorEvent'],
            'export.channels.success' => ['export.channels.success', 'AsyncExportChannelsEvent'],
            'export.moderation_logs.error' => ['export.moderation_logs.error', 'AsyncExportErrorEvent'],
            'export.moderation_logs.success' => ['export.moderation_logs.success', 'AsyncExportModerationLogsEvent'],
            'export.users.error' => ['export.users.error', 'AsyncExportErrorEvent'],
            'export.users.success' => ['export.users.success', 'AsyncExportUsersEvent'],
            'feeds.activity.added' => ['feeds.activity.added', 'ActivityAddedEvent'],
            'feeds.activity.deleted' => ['feeds.activity.deleted', 'ActivityDeletedEvent'],
            'feeds.activity.feedback' => ['feeds.activity.feedback', 'ActivityFeedbackEvent'],
            'feeds.activity.marked' => ['feeds.activity.marked', 'ActivityMarkEvent'],
            'feeds.activity.pinned' => ['feeds.activity.pinned', 'ActivityPinnedEvent'],
            'feeds.activity.reaction.added' => ['feeds.activity.reaction.added', 'ActivityReactionAddedEvent'],
            'feeds.activity.reaction.deleted' => ['feeds.activity.reaction.deleted', 'ActivityReactionDeletedEvent'],
            'feeds.activity.reaction.updated' => ['feeds.activity.reaction.updated', 'ActivityReactionUpdatedEvent'],
            'feeds.activity.removed_from_feed' => ['feeds.activity.removed_from_feed', 'ActivityRemovedFromFeedEvent'],
            'feeds.activity.restored' => ['feeds.activity.restored', 'ActivityRestoredEvent'],
            'feeds.activity.unpinned' => ['feeds.activity.unpinned', 'ActivityUnpinnedEvent'],
            'feeds.activity.updated' => ['feeds.activity.updated', 'ActivityUpdatedEvent'],
            'feeds.bookmark.added' => ['feeds.bookmark.added', 'BookmarkAddedEvent'],
            'feeds.bookmark.deleted' => ['feeds.bookmark.deleted', 'BookmarkDeletedEvent'],
            'feeds.bookmark.updated' => ['feeds.bookmark.updated', 'BookmarkUpdatedEvent'],
            'feeds.bookmark_folder.deleted' => ['feeds.bookmark_folder.deleted', 'BookmarkFolderDeletedEvent'],
            'feeds.bookmark_folder.updated' => ['feeds.bookmark_folder.updated', 'BookmarkFolderUpdatedEvent'],
            'feeds.comment.added' => ['feeds.comment.added', 'CommentAddedEvent'],
            'feeds.comment.deleted' => ['feeds.comment.deleted', 'CommentDeletedEvent'],
            'feeds.comment.reaction.added' => ['feeds.comment.reaction.added', 'CommentReactionAddedEvent'],
            'feeds.comment.reaction.deleted' => ['feeds.comment.reaction.deleted', 'CommentReactionDeletedEvent'],
            'feeds.comment.reaction.updated' => ['feeds.comment.reaction.updated', 'CommentReactionUpdatedEvent'],
            'feeds.comment.restored' => ['feeds.comment.restored', 'CommentRestoredEvent'],
            'feeds.comment.updated' => ['feeds.comment.updated', 'CommentUpdatedEvent'],
            'feeds.feed.created' => ['feeds.feed.created', 'FeedCreatedEvent'],
            'feeds.feed.deleted' => ['feeds.feed.deleted', 'FeedDeletedEvent'],
            'feeds.feed.updated' => ['feeds.feed.updated', 'FeedUpdatedEvent'],
            'feeds.feed_group.changed' => ['feeds.feed_group.changed', 'FeedGroupChangedEvent'],
            'feeds.feed_group.deleted' => ['feeds.feed_group.deleted', 'FeedGroupDeletedEvent'],
            'feeds.feed_group.restored' => ['feeds.feed_group.restored', 'FeedGroupRestoredEvent'],
            'feeds.feed_member.added' => ['feeds.feed_member.added', 'FeedMemberAddedEvent'],
            'feeds.feed_member.removed' => ['feeds.feed_member.removed', 'FeedMemberRemovedEvent'],
            'feeds.feed_member.updated' => ['feeds.feed_member.updated', 'FeedMemberUpdatedEvent'],
            'feeds.follow.created' => ['feeds.follow.created', 'FollowCreatedEvent'],
            'feeds.follow.deleted' => ['feeds.follow.deleted', 'FollowDeletedEvent'],
            'feeds.follow.updated' => ['feeds.follow.updated', 'FollowUpdatedEvent'],
            'feeds.notification_feed.updated' => ['feeds.notification_feed.updated', 'NotificationFeedUpdatedEvent'],
            'feeds.stories_feed.updated' => ['feeds.stories_feed.updated', 'StoriesFeedUpdatedEvent'],
            'flag.updated' => ['flag.updated', 'FlagUpdatedEvent'],
            'ingress.error' => ['ingress.error', 'IngressErrorEvent'],
            'ingress.started' => ['ingress.started', 'IngressStartedEvent'],
            'ingress.stopped' => ['ingress.stopped', 'IngressStoppedEvent'],
            'member.added' => ['member.added', 'MemberAddedEvent'],
            'member.removed' => ['member.removed', 'MemberRemovedEvent'],
            'member.updated' => ['member.updated', 'MemberUpdatedEvent'],
            'message.deleted' => ['message.deleted', 'MessageDeletedEvent'],
            'message.flagged' => ['message.flagged', 'MessageFlaggedEvent'],
            'message.new' => ['message.new', 'MessageNewEvent'],
            'message.pending' => ['message.pending', 'PendingMessageEvent'],
            'message.read' => ['message.read', 'MessageReadEvent'],
            'message.unblocked' => ['message.unblocked', 'MessageUnblockedEvent'],
            'message.undeleted' => ['message.undeleted', 'MessageUndeletedEvent'],
            'message.updated' => ['message.updated', 'MessageUpdatedEvent'],
            'moderation.custom_action' => ['moderation.custom_action', 'ModerationCustomActionEvent'],
            'moderation.flagged' => ['moderation.flagged', 'ModerationFlaggedEvent'],
            'moderation.mark_reviewed' => ['moderation.mark_reviewed', 'ModerationMarkReviewedEvent'],
            'moderation_check.completed' => ['moderation_check.completed', 'ModerationCheckCompletedEvent'],
            'moderation_rule.triggered' => ['moderation_rule.triggered', 'ModerationRulesTriggeredEvent'],
            'notification.mark_unread' => ['notification.mark_unread', 'NotificationMarkUnreadEvent'],
            'notification.reminder_due' => ['notification.reminder_due', 'ReminderNotificationEvent'],
            'notification.thread_message_new' => ['notification.thread_message_new', 'NotificationThreadMessageNewEvent'],
            'reaction.deleted' => ['reaction.deleted', 'ReactionDeletedEvent'],
            'reaction.new' => ['reaction.new', 'ReactionNewEvent'],
            'reaction.updated' => ['reaction.updated', 'ReactionUpdatedEvent'],
            'reminder.created' => ['reminder.created', 'ReminderCreatedEvent'],
            'reminder.deleted' => ['reminder.deleted', 'ReminderDeletedEvent'],
            'reminder.updated' => ['reminder.updated', 'ReminderUpdatedEvent'],
            'review_queue_item.new' => ['review_queue_item.new', 'ReviewQueueItemNewEvent'],
            'review_queue_item.updated' => ['review_queue_item.updated', 'ReviewQueueItemUpdatedEvent'],
            'thread.updated' => ['thread.updated', 'ThreadUpdatedEvent'],
            'user.banned' => ['user.banned', 'UserBannedEvent'],
            'user.deactivated' => ['user.deactivated', 'UserDeactivatedEvent'],
            'user.deleted' => ['user.deleted', 'UserDeletedEvent'],
            'user.flagged' => ['user.flagged', 'UserFlaggedEvent'],
            'user.messages.deleted' => ['user.messages.deleted', 'UserMessagesDeletedEvent'],
            'user.muted' => ['user.muted', 'UserMutedEvent'],
            'user.reactivated' => ['user.reactivated', 'UserReactivatedEvent'],
            'user.unbanned' => ['user.unbanned', 'UserUnbannedEvent'],
            'user.unmuted' => ['user.unmuted', 'UserUnmutedEvent'],
            'user.unread_message_reminder' => ['user.unread_message_reminder', 'UserUnreadReminderEvent'],
            'user.updated' => ['user.updated', 'UserUpdatedEvent'],
            'user_group.created' => ['user_group.created', 'UserGroupCreatedEvent'],
            'user_group.deleted' => ['user_group.deleted', 'UserGroupDeletedEvent'],
            'user_group.member_added' => ['user_group.member_added', 'UserGroupMemberAddedEvent'],
            'user_group.member_removed' => ['user_group.member_removed', 'UserGroupMemberRemovedEvent'],
            'user_group.updated' => ['user_group.updated', 'UserGroupUpdatedEvent'],
        ];
    }

    public function testParseWebhookEventUnknownType(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Unknown webhook event type');
        Webhook::parseWebhookEvent('{"type":"unknown.event"}');
    }

    public function testParseWebhookEventMissingType(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage("missing 'type' field");
        Webhook::parseWebhookEvent('{"foo":"bar"}');
    }

    public function testParseWebhookEventInvalidJson(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->expectExceptionMessage('Invalid JSON');
        Webhook::parseWebhookEvent('not json');
    }
}
