<?php

declare(strict_types=1);

namespace GetStream\GeneratedModels;
/**
 * A single client-side telemetry event. JoinInitiated is the top-level marker emitted when a user begins a join attempt and carries only join_attempt_id (no stage_id or coordinator_connect_id). When stage is CoordinatorJoin, CoordinatorWS, WSJoin, or PeerConnectionConnect the event reports a join-lifecycle attempt; initiation and completion of a stage attempt share the same stage_id. FirstAudioFrame and FirstVideoFrame report media readiness and only ever carry an initiated event. MediaDevicePermission reports the result of requesting screen-share, microphone, and camera permissions. Other stage values denote generic client events.
 */
class ClientEvent extends BaseModel
{
    public function __construct(
        public ?string $userID = null, // ID of the user the event was recorded for
        public ?string $type = null, // Call type associated with the event. Required on every stage except CoordinatorWS, where it is optional.
        public ?string $id = null, // Call ID associated with the event. Required on every stage except CoordinatorWS, where it is optional.
        public ?string $stage = null, // Discriminator identifying the event kind. JoinInitiated marks the start of a join attempt; join-lifecycle events use CoordinatorJoin, CoordinatorWS, WSJoin, or PeerConnectionConnect; media-readiness events use FirstAudioFrame or FirstVideoFrame; MediaDevicePermission reports device permission results; other values denote generic client events.
        public ?string $stageID = null, // UUID generated by the client at initiation. Identical on the matching completion event. Absent on JoinInitiated.
        public ?string $joinAttemptID = null, // UUID generated by the client and shared across JoinInitiated and the join-lifecycle events (CoordinatorJoin, WSJoin, PeerConnectionConnect) of the same overall join attempt. Required on every join event except CoordinatorWS, which is reported before a join attempt is established.
        public ?string $coordinatorConnectID = null, // UUID generated by the client and shared across every event of the same coordinator connection. Required on every event except JoinInitiated, which is reported before a coordinator connection exists.
        public ?string $eventType = null, // Whether the event marks the start (initiated) or resolution (completed) of a stage attempt, or another event-specific value
        public ?\DateTime $timestamp = null, // UTC timestamp at which the event was recorded
        public ?string $userAgent = null, // User agent string of the client SDK
        public ?string $sdkVersion = null, // Version of the client SDK
        public ?string $peerConnection = null, // Which peer connection a PeerConnectionConnect event reports on: publish or subscribe. Required on every PeerConnectionConnect event.
        public ?bool $wasPreviouslyConnected = null, // Whether the ICE connection had been established earlier in the same session. Required on every PeerConnectionConnect event so reconnects can be distinguished from fresh connects.
        public ?\DateTime $previouslyConnectedTimestamp = null, // UTC timestamp at which the ICE connection was established earlier in the session, when applicable
        public ?string $outcome = null, // Resolution of a completed event: success or failure. Required on completed join events; forbidden on initiated join events.
        public ?int $retryCountAttempt = null, // Total in-stage retries the client made before resolving (0–1000). Required on completed join events.
        public ?int $elapsedTime = null, // Milliseconds elapsed between the stage attempt's initiation and this event. 
        public ?string $callSessionID = null, // Call session ID associated with the attempt. Required on every event except CoordinatorJoin initiation and CoordinatorJoin failure (where the call session is not yet established); optional on MediaDevicePermission.
        public ?string $joinReason = null, // Reason the client initiated the join. Optional on CoordinatorJoin events; empty when not provided.
        public ?string $sfuID = null, // Identifier of the SFU the client was attempting to connect to. Required on WSJoin and PeerConnectionConnect failure, and on FirstAudioFrame and FirstVideoFrame.
        public ?string $trackID = null, // Identifier of the media track the frame belongs to. Required on FirstVideoFrame; optional on FirstAudioFrame.
        public ?string $retryFailureReason = null, // Failure reason string. Required on CoordinatorJoin, CoordinatorWS, WSJoin, and PeerConnectionConnect failure.
        public ?string $retryFailureCode = null, // Failure code string. Required on CoordinatorJoin, CoordinatorWS, WSJoin, and PeerConnectionConnect failure.
        public ?string $iceState = null, // Terminal state of the peer connection. Required on PeerConnectionConnect failure.
        public ?string $screenShareStatus = null, // Screen-share permission status: INITIATED, FAILED, GRANTED, or NOT_INITIATED. Optional on MediaDevicePermission events.
        public ?string $microphonePermissionStatus = null, // Microphone permission status: INITIATED, FAILED, GRANTED, or NOT_INITIATED. Required on every MediaDevicePermission event.
        public ?string $cameraPermissionStatus = null, // Camera permission status: INITIATED, FAILED, GRANTED, or NOT_INITIATED. Required on every MediaDevicePermission event.
    ) {
    }

    // BaseModel automatically handles jsonSerialize(), toArray(), and fromJson() using constructor types!
    // Use #[JsonKey('user_id')] to override field names if needed.
}
