<?php
// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

declare(strict_types=1);

namespace GetStream\Exceptions;

/**
 * Thrown for every webhook handling failure: signature mismatch, invalid JSON,
 * missing/non-string `type` field, gzip-prefixed body that fails to decompress,
 * invalid base64 in a queue body, or a malformed SNS envelope.
 *
 * The unified class replaces the earlier split (separate signature vs. malformed
 * exceptions): customers distinguish failure modes via the exception's message
 * substring or its previous chain ({@see \Throwable::getPrevious()}) rather than
 * its class.
 */
class InvalidWebhookException extends StreamException
{
}
