<?php
// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

declare(strict_types=1);

namespace GetStream\Exceptions;

/**
 * Thrown when the X-Signature header does not match the HMAC-SHA256 of the
 * body under the configured webhook secret. Treat as a security failure: log
 * the source and reject the request (HTTP 401/403).
 */
class InvalidSignatureException extends WebhookException
{
}
