<?php
// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

declare(strict_types=1);

namespace GetStream\Exceptions;

/**
 * Thrown for every webhook handling failure: signature mismatch, invalid JSON,
 * missing/non-string `type` field, gzip-prefixed body that fails to decompress,
 * invalid base64 in a queue body, or a malformed SNS envelope.
 *
 * Catch this single class for any webhook problem; filter on the message text
 * or against the failure-mode constants below to differentiate.
 */
class InvalidWebhookException extends StreamException
{
    public const SIGNATURE_MISMATCH = 'signature mismatch';
    public const INVALID_BASE64 = 'invalid base64 encoding';
    public const GZIP_FAILED = 'gzip decompression failed';
    public const INVALID_JSON = 'invalid JSON payload';
}
