<?php
// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

declare(strict_types=1);

namespace GetStream\Exceptions;

/**
 * Thrown when the webhook body could not be parsed: invalid JSON,
 * missing/non-string `type` field, gzip decompression failure, base64
 * failure, or malformed SNS envelope. Treat as a client/format problem
 * (HTTP 400).
 */
class MalformedWebhookException extends WebhookException
{
}
