<?php
// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

declare(strict_types=1);

namespace GetStream\Exceptions;

/**
 * Base exception for every webhook handling failure. Catch
 * {@see WebhookException} for a single arm that covers all failure modes, or
 * one of its subclasses ({@see InvalidSignatureException},
 * {@see MalformedWebhookException}) to distinguish security failures from
 * parse failures.
 */
class WebhookException extends StreamException
{
}
