<?php
// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

declare(strict_types=1);

namespace GetStream\Models;

/**
 * Returned by Webhook::parseEvent when the type discriminator is well-formed
 * but unknown to this SDK version. Forward-compat surface for new event types.
 *
 * To handle unknown events, check the result type with `instanceof UnknownEvent`
 * after calling `parseEvent`.
 */
class UnknownEvent
{
    public function __construct(
        /** The unrecognized discriminator value. */
        public readonly string $type,
        /** Parsed timestamp from the envelope, or null if the field was missing or unparseable. */
        public readonly ?\DateTimeImmutable $createdAt,
        /** The full parsed JSON payload, for inspection. */
        public readonly array $raw,
    ) {
    }

    public function getType(): string
    {
        return $this->type;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getRaw(): array
    {
        return $this->raw;
    }
}
