<?php
// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

declare(strict_types=1);

namespace GetStream;

require_once __DIR__ . '/Generated/Webhook.php';

/**
 * Canonical name for the webhook helper. Inherits all static helpers from
 * GetStream\Generated\Webhook so the PSR-4 autoloader (which maps
 * GetStream\\ -> src/) can resolve `\GetStream\Webhook` directly, and so
 * static analyzers (PHPStan, Psalm) can see the class without following the
 * runtime class_alias chain.
 *
 * Static method calls behave identically to GetStream\Generated\Webhook —
 * see that class for the canonical API surface.
 */
class Webhook extends \GetStream\Generated\Webhook
{
}
