name: ci

on: 
  pull_request:
  push:
    branches: [master, main]

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: 🧪 Test & lint
    environment: ci
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: curl, json
        tools: composer:v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction

    - name: Test
      env:
        STREAM_API_KEY: ${{ vars.STREAM_API_KEY }}
        STREAM_API_SECRET: ${{ secrets.STREAM_API_SECRET }}
      run: |
        make lint
        make test
